# Generated by Django 4.1 on 2022-09-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CER', '0002_cec_course_learning_style_cec_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cec_course',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('S', 'SELF PACED'), ('I', 'INSTRUCTOR LED')], max_length=2, null=True),
        ),
    ]
