# Generated by Django 4.1 on 2022-08-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSRM', '0003_alter_csrm_institution_status_alter_csrm_user_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csrm_institution',
            old_name='desciption',
            new_name='description',
        ),
    ]
