# Generated by Django 4.1 on 2022-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0002_cat_course_group_cat_course_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_course',
            name='course_pacing',
            field=models.CharField(choices=[('I', 'INSTRUCTOR-LED'), ('S', 'SELF-PACED')], default='I', max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='enrollment_type',
            field=models.CharField(choices=[('O', 'OPEN'), ('B', 'BY_INVITATION')], default='O', max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='language',
            field=models.CharField(choices=[('E', 'ENGLISH'), ('F', 'FRENCH'), ('C', 'CHINESE'), ('Y', 'YORUBA'), ('H', 'HAUSA'), ('I', 'IGBO')], default='E', max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='level',
            field=models.CharField(choices=[('I', 'INTRODUCTORY'), ('IN', 'INTERMEDIATE'), ('A', 'ADVANCED')], default='I', max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('DN', 'DRAFT(NEVER PUBLISHED)'), ('P', 'PUBLISHED(NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('DU', 'DRAFT(UNPUBLISHED CHANGES)')], default='DN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_component',
            name='exercise_type',
            field=models.CharField(choices=[('V', 'QUIZ'), ('Y', 'ONLINETEST'), ('M', 'OFFLINETEST')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_component',
            name='html_type',
            field=models.CharField(choices=[('H', 'HTML'), ('I', 'IFRAME')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_component',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGE'), ('H', 'HTML'), ('E', 'EXERCISE')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course_component',
            name='video_type',
            field=models.CharField(choices=[('V', 'VIMEO'), ('Y', 'YOUTUBE'), ('M', 'MP4'), ('WZ', 'WEBINAR ON ZOOM'), ('ME', 'MEETING ON ZOOM'), ('WV', 'WEBINAR ON VIMEO')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_group',
            name='type',
            field=models.CharField(choices=[('A', 'ADMIN'), ('A', 'AUTHOR'), ('L', 'LEARNER')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course_lesson',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('DN', 'DRAFT(NEVER PUBLISHED)'), ('P', 'PUBLISHED(NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('DU', 'DRAFT(UNPUBLISHED CHANGES)')], default='DN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_question',
            name='type',
            field=models.CharField(choices=[('T', 'TEXT'), ('N', 'NUMBER'), ('R', 'RADIOBUTTON'), ('C', 'CHECKBOX'), ('DR', 'DROPDOWN'), ('E', 'ESSAY'), ('D', 'DISCUSSION')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_course_section',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('DN', 'DRAFT(NEVER PUBLISHED)'), ('P', 'PUBLISHED(NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('DU', 'DRAFT(UNPUBLISHED CHANGES)')], default='DN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_subsection',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('DN', 'DRAFT(NEVER PUBLISHED)'), ('P', 'PUBLISHED(NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('DU', 'DRAFT(UNPUBLISHED CHANGES)')], default='DN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course_team',
            name='role',
            field=models.CharField(choices=[('S', 'STAFF'), ('L', 'LEAD'), ('A', 'AUTHOR'), ('R', 'READER')], default='L', max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_courses_resources',
            name='type',
            field=models.CharField(choices=[('I', 'IMAGE'), ('V', 'VIDEO'), ('H', 'HTML'), ('P', 'PDF'), ('W', 'WORD'), ('E', 'EXCEL'), ('PP', 'POWERPOINT'), ('O', 'OTHERS')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='age',
            field=models.CharField(blank=True, choices=[('<18', 'UNDER 18'), ('18-24', 'BETWEEN 18 AND 24'), ('25-34', 'BETWEEN 35 AND 44'), ('45-54', 'BETWEEN 45 AND 54'), ('55-64', 'BETWEEN 55 AND 64'), ('65-74', 'BETWEEN 65 AND 74'), ('>75', 'OLDER THAN 75')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('S', 'STUDENT'), ('U', 'UNEMPLOYED'), ('SE', 'SELF-EMPLOYED'), ('CE', 'COMAPNY-EMPLOYED'), ('OM', 'OWNER-MANAGER')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('B', 'BEGINNER'), ('I', 'INTERMEDIATE'), ('E', 'EXPERT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('NOT', 'NOT DECLARED')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='language',
            field=models.CharField(choices=[('E', 'ENGLISH'), ('F', 'FRENCH'), ('C', 'CHINESE')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='marital_status',
            field=models.CharField(choices=[('S', 'SINGLE'), ('M', 'MARRIED'), ('D/W', 'DIVORCED/WIDOWED'), ('NOT', 'NOT DECLARED')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cat_instructor',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'ACTIVE'), ('M', 'MERGED'), ('D', 'DEACTIVATED')], max_length=4, null=True),
        ),
    ]
