# Generated by Django 4.1 on 2022-09-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0005_alter_cat_course_created_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_course',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='visible_to_authoring_team',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat_course',
            name='visible_to_student_groups',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
