# Generated by Django 4.1 on 2022-09-05 04:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CSRM', '0004_rename_desciption_csrm_institution_description'),
        ('CAT', '0003_alter_cat_course_course_pacing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMS_Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('VI', 'VIDEO'), ('IM', 'IMAGE'), ('HT', 'HTML'), ('EX', 'EXERCISE')], max_length=2)),
                ('video_type', models.CharField(choices=[('VI', 'VIMEO'), ('YO', 'YOUTUBE'), ('MP', 'MP4'), ('WZ', 'WEBINAR ON ZOOM'), ('ME', 'MEETING ON ZOOM'), ('WV', 'WEBINAR ON VIMEO')], max_length=2, null=True)),
                ('video_header', models.CharField(max_length=250, null=True)),
                ('video_footer', models.CharField(max_length=250, null=True)),
                ('recorded_url', models.CharField(max_length=250, null=True)),
                ('live_url', models.CharField(max_length=250, null=True)),
                ('mobile_url', models.CharField(max_length=250, null=True)),
                ('starting_date_time', models.CharField(max_length=250, null=True)),
                ('image_header', models.CharField(max_length=250, null=True)),
                ('image_footer', models.CharField(max_length=250, null=True)),
                ('image_url', models.URLField(null=True)),
                ('html_title', models.CharField(max_length=250, null=True)),
                ('html_type', models.CharField(choices=[('HT', 'HTML'), ('IF', 'IFRAME')], max_length=2, null=True)),
                ('html_content', models.TextField(null=True)),
                ('html_url', models.CharField(max_length=250, null=True)),
                ('exercise_type', models.CharField(choices=[('QI', 'QUIZ'), ('ON', 'ONLINETEST'), ('OF', 'OFFLINETEST')], max_length=2, null=True)),
                ('grading_weight', models.IntegerField(default=0, null=True)),
                ('total_score', models.IntegerField(null=True)),
                ('available_date_time', models.DateTimeField(null=True)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('due_date_time', models.DateTimeField(null=True)),
                ('show_allocated_score', models.BooleanField(null=True)),
                ('show_hint', models.BooleanField(null=True)),
                ('show_answer', models.BooleanField(null=True)),
                ('exercise_overview', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LMS_Component',
            },
        ),
        migrations.CreateModel(
            name='LMS_Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('visible_to_authoring_team', models.BooleanField(blank=True, default=True, null=True)),
                ('visible_to_student_groups', models.BooleanField(blank=True, default=False, null=True)),
                ('publication_status', models.CharField(blank=True, choices=[('NP', 'DRAFT (NEVER PUBLISHED)'), ('NR', 'PUBLISHED (NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('UC', 'DRAFT (UNPUBLISHED CHANGES)'), ('AR', 'ARCHIVED'), ('ER', 'EXPIRED AND REPLACED'), ('EN', 'EXPIRED AND NOT REPLACED')], default='NP', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cat_course_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CAT.cat_course')),
                ('institution_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='CSRM.csrm_institution')),
            ],
            options={
                'db_table': 'LMS_Course',
            },
        ),
        migrations.CreateModel(
            name='LMS_Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_no', models.IntegerField()),
                ('type', models.CharField(choices=[('TE', 'TEXT'), ('NU', 'NUMBER'), ('RA', 'RADIOBUTTON'), ('CH', 'CHECKBOX'), ('DR', 'DROPDOWN'), ('ES', 'ESSAY'), ('DI', 'DISCUSSION')], max_length=2)),
                ('question', models.FileField(upload_to=None)),
                ('option1', models.CharField(max_length=250)),
                ('option2', models.CharField(max_length=250)),
                ('option3', models.CharField(max_length=250)),
                ('option4', models.CharField(max_length=250)),
                ('option5', models.CharField(max_length=250)),
                ('answer_text', models.CharField(max_length=250)),
                ('answer_number', models.CharField(max_length=250)),
                ('answer_options', models.CharField(max_length=10)),
                ('hint', models.FileField(upload_to=None)),
                ('feedback', models.FileField(upload_to=None)),
                ('allocated_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('component_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='LMS.lms_component')),
            ],
            options={
                'db_table': 'LMS_Question',
            },
        ),
        migrations.CreateModel(
            name='LMS_Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(blank=True, choices=[('SE', 'SESSION)'), ('SU', 'SUBSECTION)'), ('LE', 'LESSON')], default='SE', max_length=2, null=True)),
                ('row_id', models.UUIDField()),
                ('position_id', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=250, null=True)),
                ('overview', models.TextField(null=True)),
                ('component_types', models.CharField(max_length=11, null=True)),
                ('rights_ro', models.CharField(max_length=250, null=True)),
                ('rights_none', models.CharField(max_length=250, null=True)),
                ('publication_status', models.CharField(blank=True, choices=[('NP', 'DRAFT (NEVER PUBLISHED)'), ('NR', 'PUBLISHED (NOT YET RELEASED)'), ('PL', 'PUBLISHED AND LIVE'), ('UC', 'DRAFT (UNPUBLISHED CHANGES)'), ('AR', 'ARCHIVED'), ('ER', 'EXPIRED AND REPLACED'), ('EN', 'EXPIRED AND NOT REPLACED')], default='NP', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='LMS.lms_course')),
            ],
            options={
                'db_table': 'LMS_Page',
                'ordering': ['position_id'],
            },
        ),
        migrations.CreateModel(
            name='LMS_Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_position_id', models.TextField(null=True)),
                ('enrollment_status', models.CharField(max_length=100, null=True)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.lms_course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRM.csrm_user')),
            ],
        ),
        migrations.AddField(
            model_name='lms_component',
            name='page_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='LMS.lms_page'),
        ),
        migrations.CreateModel(
            name='LMS_BookmarkComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bookmarked', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrolment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.lms_enrollment')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.lms_bookmarkcomment')),
            ],
        ),
    ]
