# Generated by Django 4.1 on 2022-09-05 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms_page',
            name='row_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
